### ISSUE TITLE
tidy up repo

### ISSUE THREAD

**Issue by RosaWagner** [googlefonts/Unified-Font-Repository#38]
I would be in favor to clean up this repo so at root we only have:
- licence
- contributors
- authors
- readme
- .gitignore
- requirements

What I mean is: would it make sense to move `makefile` and `.json` file in a script directory? It would also encourage designers to put their scripts there instead of everywhere.

**Comment by simoncozens** [comment]
The `.templaterc.json` is a dot-file, meaning you won't normally see it in your working directory. We have a `scripts` directory already. So that leaves the Makefile, and I personally prefer having that at the root, because then it's obvious how to build the font - you don't have to go searching around to find the build script.
