### ISSUE TITLE
image1.py: suggestions

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/Unified-Font-Repository#50]
- Dynamically pick a font to use. The user currently has to edit the `FONT_PATH` variable
- For the `FONT_NAME` variable, use either nameID16 if it exists or just use nameID1 if the font is RIBBI. Atm, we are using the full name which ends up including the style name. This can look quite messy for variable fonts. Imo it is better to just have the "best" family name.

Nit. It may be cool to move away from the "Aa" sample text. Perhaps we could render the font's name instead? I get that some families may not include Latin though in which case both "Aa" and Latin font name will fail.

**Comment by m4rc1e** [comment]
I've been drafting a font picking heuristic this morning and it's going to be too complex if we need to cover all edge cases. Instead I suggest we add the font_path as an cli arg to the script. All the constants you've provided can also be included as optional cli args

**Comment by simoncozens** [comment]
I think the point of this script was *not* to magically produce a good sample for any arbitrary font, but to be a well-commented starting point for designers to script their own sample image generation.

That's why we didn't go down the route of guessing the font filename and parameters; there's an expectation that the designer will edit it.
